version: '3.0'

volumes:
  script-neo4j:

services:
  neo4j:
    image: neo4j:latest
    container_name: script-neo4j
    ports:
      - '7475:7474'
      - '7688:7687'

    env_file:
      - path: .env
        required: true

    volumes:
      - script-neo4j:/data


