version: '3.0'

volumes:
  gg-neo4j:
  uet2-neo4j:
  test2-neo4j:
  test3-neo4j:

services:
  neo4j:
    image: neo4j:latest
    container_name: gg-neo4j
    ports:
      - '7474:7474'
      - '7687:7687'

    env_file:
      - path: .env
        required: true

    volumes:
      - test3-neo4j:/data


