version: '3.0'

volumes:
  uet2-neo4j:

services:
  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'

    env_file:
      - path: .env
        required: true

    volumes:
      - uet2-neo4j:/data


